### ISSUE TITLE
Team data gets deleted in Chrome when switching from HTTP to HTTPS

### ISSUE THREAD

**Issue by sobolews** [Zarel/Pokemon-Showdown-Client#455] opened 2015-08-31 05:28 UTC
In Google Chrome, the teams stored in localStorage get deleted when the teams are created on the HTTP version of the website, then accessed via the HTTPS version. They remain deleted even after switching back to HTTP.

I've tested this scenario on Ubuntu/Chrome 40.0 and OS X 10.10/Chrome 44.0. According to a user in the help room, this occurs under Windows 7 as well, and performing a system restore causes the teams to be restored.

**Comment by StAlRuth** [comment] 2015-09-01 02:03
Tried it once and it worked, however after restoring my teams the bug seems fixed.

Chromium 44.0.2403.89 on Ubuntu 15.10

**Comment by Zarel** [comment] 2015-09-01 04:14
I've had this happen, too, and seen it happen to other people. In theory, we've set up a system for communication between HTTP and HTTPS versions, but it appears to be problematic. I'll have to investigate further.

**Comment by KitKasai** [comment] 2015-09-26 05:31
I was going to post an issue for a different problem but it seems to be related so I'll put it here. Feel free to move it to a separate issue if it's significantly different; I can't really tell from a technical standpoint.

It's an issue regarding the autojoin feature.
So I read that the autojoin feature worked by keeping the first 4 rooms that you had open before you closed the window and sets those as your autojoin rooms. It didn't work for me so I investigated what was going on by looking at what was stored in the local storage for the page. Turns out that it does properly store the autojoin rooms, but if you're using https it stores the localstorage data in a separate entry. Problem is when you join showdown, instead of loading the localstorage data in the https entry for the website, it loads the data from the http entry.

**Comment by Zarel** [comment] 2015-09-26 05:55
> Problem is when you join showdown, instead of loading the localstorage data in the https entry for the website, it loads the data from the http entry

Are you sure that's the problem? Have you read the code? I'm pretty sure the problem is more complicated than that.

**Comment by KitKasai** [comment] 2015-09-26 06:47
Should have clarified, that's what it appears to be doing. I have no idea how to fix it, just reporting the bug.

**Comment by Zarel** [comment] 2015-09-26 18:00
Okay, just to clarify from this end.

The intended behavior is for PS in HTTP is to load data from HTTPS if it exists, or from HTTP otherwise. Most likely, something broke in the code that loads data from HTTPS to HTTP.

**Comment by StAlRuth** [comment] 2015-09-27 01:00
That explains why my problem was solved then.

What's meant to happen in the scenario that you use showdown in HTTP, then switch to HTTPS?

Because we're losing all of our teams but thanks to the behaviour you mentioned I haven't had the issue since.

**Comment by augmt** [comment] 2015-10-23 16:11
The teams aren't actually being deleted; they're being overlooked.

If an user makes a team on HTTP and switches to HTTPS, the client won't load the HTTP team as [this code in client.js](https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/js/client.js#L604-L613) has been commented out.

When the user switches back to HTTP, the user's HTTPS team is loaded instead, which is as intended.

**Comment by Zarel** [comment] 2016-02-16 22:01
This was fixed in cf8bb24e719a8

**Closed by Zarel** 2016-02-16 22:01 UTC
