### ISSUE TITLE
Support showing stats for servers with custom mods

### ISSUE THREAD

**Issue by DeathlyPlays** [Zarel/Pokemon-Showdown-Client#986] opened 2017-08-24 13:01 UTC
I was wondering if there would be a way to make the type, description, base power, accuracy, etc show up based off the mod/ folder on the server rather than the data.

**Comment by Zarel** [comment] 2017-08-24 20:09
Yes, that's planned, and I'm pretty sure we already have an issue for it.

**Comment by DeathlyPlays** [comment] 2017-08-24 20:22
Oh you do then I can close this one :)

**Comment by Zarel** [comment] 2017-08-24 20:52
I can't actually find the issue for it... >_<

**Comment by DeathlyPlays** [comment] 2017-08-24 21:00
Tbh neither could I @Zarel

**Comment by Marty-D** [comment] 2017-08-24 21:01
@Zarel there's no issue for it because you already did this a long time ago. @DeathlyPlays why did you open this without checking that it's already implemented? Everything you mentioned already exists; the only thing that could be improved at this point is using the long description instead of the short one.

**Comment by DeathlyPlays** [comment] 2017-08-24 21:04
Mmm I thought it wasn't the Mod folders descriptions but I was more implying like new moves etc

**Comment by Marty-D** [comment] 2017-08-24 21:07
Are you talking about custom things? Why didn't you mention that anywhere? It sounded like you were just talking about past gens.

**Comment by Zarel** [comment] 2017-08-24 21:07
@Marty-D I did this for official mods. I don't know _exactly_ what this issue is asking for, but having support for custom mods is still on the to-do list.

**Comment by Zarel** [comment] 2017-08-24 21:31
But really, ick, this title.

**Comment by DeathlyPlays** [comment] 2017-08-24 21:33
Yea I didn't know exactly how to present the "issue"

**Comment by Zarel** [comment] 2017-08-24 21:35
So basically, what I actually want to do is for the server to send to the client new teambuilder tables. The hard part is investigating how much sanitization the teambuilder tables need, client-side.

And, of course, porting the client side table building code to the server.

**Comment by DeathlyPlays** [comment] 2017-08-24 21:38
Oh you are also going to like get the Teambuilder end fixed too where it shows the moves it can now learn etc and possibly add the new moves it can learn?

**Comment by Zarel** [comment] 2017-08-24 23:43
Yeah.

**Comment by Zarel** [comment] 2017-08-24 23:44
Honestly, if you could generate teambuilder tables, that'd solve the problem for me.

**Comment by DeathlyPlays** [comment] 2017-08-25 10:26
Tbh I'm not at all familiar with Client code e_e plus idk a service I could use to test it

**Comment by AustinXII** [comment] 2017-08-25 15:44
Testing a new client isn't hard to do but yeah understanding the PS client code is

**Comment by Zarel** [comment] 2017-08-25 19:36
You don't need to involve yourself in the rest of the client to use the teambuilder table; it's reasonably isolated.

https://github.com/Zarel/Pokemon-Showdown-Client/blob/051f16287e488ad9a870038aa8557f557d8a087d/githooks/build-indexes#L262-L264

**Comment by Zarel** [comment] 2017-09-06 08:06
duplicate of Zarel/Pokemon-Showdown#2557

**Comment by Zarel** [comment] 2017-09-06 08:07
I _knew_ there was already an issue for this...

**Closed** 2017-09-06 08:07 UTC
