### ISSUE TITLE
Animation Capability 

### ISSUE THREAD

**Issue by Lord-Haji** [Zarel/Pokemon-Showdown-Client#817] opened 2016-11-25 09:13 UTC
PS doesn't support animation capabilities for its background with its custom.css

**Comment by Zarel** [comment] 2016-11-25 18:28
Duplicate of #248

**Closed by Zarel** 2016-11-25 18:28 UTC

**Comment by Zarel** [comment] 2016-11-25 19:54
I believe the last five things you've submitted to PS's issue tracker do nothing but waste time. I would suggest talking about things in the Dev chatroom first, because this is untenable and I really don't want the issue tracker to be full of this sort of thing.
