### ISSUE TITLE
Transform + Hidden Power + Bottle Caps

### ISSUE THREAD

**Issue by Yoshizilla315** [Zarel/Pokemon-Showdown-Client#1015] opened 2017-09-30 00:24 UTC
So since this was a discussion we had on PS! I thought I'd include it here because it'll probably get it done faster. Currently, we have a missing mechanic with Showdown separating Hidden Power IVs and bottle capped IVs. For those who don't understand this mechanic, this link will help: https://youtu.be/FRI5PSekhR4?t=12m50s. 

So, there have been a few proposed solutions to this problem. For one, we could make a key-press oriented function to toggle between Hidden Power IVs and Bottle Cap IVs. Another solution was that we could make a new column in a separate window in the team builder that would display both Hidden Power IVs, and Bottle Cap IVs. This would help users visualize the actual process better. Lastly, an idea was brought up that we could use a drop down menu to change to bottle cap IVs.

Now, a few have said that this is too minuscule to implement, but personally, I believe we should be as accurate to the real game as possible, since this is a simulation after all. I wanted to get everyone's thoughts on this problem, as many of us seem to disagree on a solution, and if there should be one at all.

**Comment by Zarel** [comment] 2017-09-30 02:40
Duplicate of Zarel/Pokemon-Showdown#3073

**Closed by Zarel** 2017-09-30 02:40 UTC

**Comment by Zarel** [comment] 2017-09-30 06:20
There's no need to brainstorm solutions because I've already settled on using a Hidden Power type dropdown. Unless you think something else is better (currently I don't think anyone does).
