### ISSUE TITLE
PP Tracker for foe Pokémon ignores hidden ability changes

### ISSUE THREAD

**Issue by JsKingBoo** [Zarel/Pokemon-Showdown-Client#766] opened 2016-09-15 00:03 UTC
This leads to a situation where the opponent's PP counter reaches a negative counter.

http://i.imgur.com/96MHn00.png

In the screenshot above, the Leppa Berry triggered on Remoraid's Fire Blast, allowing it to appear as though it has been used 32 times when it actually has been used 16 times.

Switching out and back in does not seem to correct the PP counter.

**Comment by Slayer95** [comment] 2016-09-15 01:08
This seems to be a consequence of the foe's PP tracker thinking that you still have Pressure, since it uses the publicly available information.

Therefore, this can probably be reproduced in DPP doubles by using Skill Swap to a Pokemon with Pressure, and that makes this into scope.

I don't see any benefit in <em>not</em> using the best available information (i.e. from the request data) for tracking foe PPs, as opposed to the tooltop

**Comment by Slayer95** [comment] 2016-09-15 01:11
Blah missclick <.<

I don't see any benefit in <em>not</em> using the best available information (i.e. from the request data) for tracking foe PPs, as opposed to the tooltip for your own Pokemon.

At least for the 2 players case!

**Comment by Zarel** [comment] 2016-09-15 05:56
Skill Swap specifies the ability... This isn't a bug outside of Mix and Mega...

**Comment by ascriptmaster** [comment] 2016-09-15 06:08
Does Aerodactyl with Pressure as its base ability interact properly with the tracker after it goes mega?

**Comment by Zarel** [comment] 2016-09-15 06:53
I don't actually know. Possibly. In theory, mega evolution should change the ability.

**Comment by Slayer95** [comment] 2016-09-15 07:44
Not in DPP for allies, @Zarel

**Comment by Zarel** [comment] 2016-09-15 08:05
Even if it doesn't, PS knows to update its knowledge of abilities, or at least it should in theory.

**Comment by Slayer95** [comment] 2016-09-15 08:12
Yea it <em>should</em>
https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/js/battle.js#L5214

**Comment by Zarel** [comment] 2016-09-15 08:26
Looks like Marty did this:

https://github.com/Zarel/Pokemon-Showdown-Client/commit/b7f7ca6d64350fad1b5480332b5ee7433a8e114f

Why?

**Comment by Marty-D** [comment] 2016-09-15 12:53
Skill Swap has never displayed a message for the specific Abilities swapped in any generation. The only reason anything is revealed in Gen 5+ is because *all* Ability changes (other than as a result of a forme change) are displayed on screen with the Ability animations, unless multiple Pokemon are simultaneously having their Abilities changed and are on the same side (i.e. Skill Swap).

**Comment by Zarel** [comment] 2016-09-17 11:47
You could've added that line 10 lines later, so it wouldn't have given the message but would still have swapped the abilities.

**Comment by Zarel** [comment] 2016-09-17 11:47
Unless I'm missing something?

**Comment by Marty-D** [comment] 2016-09-17 15:08
The whole point is not revealing information the game doesn't give you. In fact, whoever added those 10 lines already caused an information leak: http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/page-276#post-6927843

**Comment by Zarel** [comment] 2016-09-17 15:31
It's a client implementation; the information leak is on the server side.

**Comment by Zarel** [comment] 2016-09-17 15:34
Like, I presume this is what you're looking for?

82c041b09a

**Comment by Zarel** [comment] 2016-09-17 15:41
Okay, I understand now, but information leaks should be fixed server-side, not client-side.

**Comment by Marty-D** [comment] 2016-09-17 15:56
Oh, I didn't realize the server implementation changed since I last looked at it. That is better, yeah, thanks! Unfortunately we're still going to get people complaining that the client is lying to them when they see both opponents with the same current Ability (the one that was already known). The balance between easy access to information and misleading information is pretty tricky.

**Comment by Zarel** [comment] 2016-09-17 17:23
I mean, I changed it when I made my post. I was just asking why you changed the client instead of the server when you fixed it...

It's not going to show both opponents with the same current ability, anyway. The client degrades gracefully.

**Comment by Zarel** [comment] 2018-10-17 00:34
We now have a Pressure warning:

https://github.com/Zarel/Pokemon-Showdown-Client/commit/91b1f2d833d61901fa6bb0c24bfde412c15e6a7c

It _is_ possible, in most cases, to correctly track Pressure PP in Gen 3.

Not for spectators, but both players know when the opponent has Pressure (by looking at their own PP), and when their own Pokémon have Pressure (you always know what Ability your own Pokémon have).

So, on switch-in, battles can use `|split` to send players silent Pressure activations. This is actually all that needs to be done; the PS client will handle everything else automatically.

**Closed** 2018-10-17 02:00 UTC
Labels: enhancement
